apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yawws4gbd-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/yawws4gbd-dotnet-basic-gitops